name: Tests
on: [push, pull_request]
jobs:
  test:
    env:
      NODE_ENV: development
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test
        run: |
          npm install
          FORCE_COLOR= npx c8 --reporter=lcov npm test && npx codecov

